### ISSUE TITLE
Bridge #sysadmin and #projects to Freenode

### ISSUE THREAD

**Issue by ct-martin** [RITlug/config-management#15]
So people not on Slack can participate

**Comment by justwheel** [comment]
`#sysadmin` on Slack is already bridged to `#rit-lug-sysadmin` on Freenode.

**Comment by Tjzabel** [comment]
@jwflory what steps can we take to bridge `#projects` to freenode? I'm assuming this is a matterbridge issue?

**Comment by Tjzabel** [comment]
[Looking here](https://github.com/FOSSRIT/infrastructure/blob/master/roles/matterbridge/vars/main.yml#L29-L34) I see the matterbridge configurations. 

It says the `#sysadmin` channel's slack bot name should be `mb-ritlug-sysadm`. Am I reading this wrong? I ask because there is no user by that name, but rather by the `slack-ritlug` user. Has the ansible playbook for matterbridge not been updated/ran properly to reflect this name?

**Comment by justwheel** [comment]
> @jwflory what steps can we take to bridge `#projects` to freenode? I'm assuming this is a matterbridge issue?

This can be a new issue filed on [FOSSRIT/infrastructure](https://github.com/FOSSRIT/infrastructure). I can grab it later this week.

> It says the `#sysadmin` channel's slack bot name should be `mb-ritlug-sysadm`. Am I reading this wrong? I ask because there is no user by that name, but rather by the `slack-ritlug` user. Has the ansible playbook for matterbridge not been updated/ran properly to reflect this name?

This is true for all the other bots as well. ~~I can't remember if `bot_name` is different from the bot's nick. It may not be necessary but need to check upstream docs for clarification.~~ I wasn't looking closely enough. I can't remember why I made a `bot_name` field. :woman_shrugging: It can probably be omitted without issue.

**Comment by Tjzabel** [comment]
@jwflory I added this as an issue there :+1:

**Comment by ct-martin** [comment]
For reference: https://github.com/FOSSRIT/infrastructure/issues/41

**Comment by Tjzabel** [comment]
This was completed.
