### ISSUE TITLE
Set up TigerOS Infrastructure

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/config-management#16]
# What This Is
TigerOS needs new infrastructure in order to continue. These items include:
* New RITlug GitLab
* Package Mirror
* Package + ISO Builder
* TeleIRC bridge for communication

## RITlug GitLab
In order to mark this action item as complete, we need:
- [ ] GitLab Ansible playbook
  * ansible galaxy playbook lives [here](https://galaxy.ansible.com/geerlingguy/gitlab)

## TigerOS Package Mirror
- [ ] Ansible playbook (not super required for move, but will be nice to have)
  * Does not require many resources to operate
- [ ] Move package mirror to new RITlug infra

## TigerOS Package Builder
- [ ] Create simple Ansible playbook and/or just spin up a VM
  * Need to figure out optimal RAM, CPU usage for building
- [x] Move (broken) builder to new RITlug infra

## TeleIRC 
- [x] Talk to Justin to figure out best way to set up bridge
  * Bridge between `#rit-tigeros` on freenode, and TigerOS Telegram group

# Next Steps
We need to figure out how we can divy up this work in order to most efficiently complete these tasks.

Furthermore, we also need to discuss *where* these playbooks/infra-related repositories will live. Some may want to live under the TigerOS group, while other repos like the GitLab ansible playbook may want to live in this repo.

**Comment by ct-martin** [comment]
As part of RITlug/TigerOS#29 & RITlug/TigerOS#147 the new build infra for TigerOS will not need its own box as it will use a GitLab CI Runner (which is already set up & registered to multiple GitLab instances but not in a playbook yet).

Mirrors will be made more generic so we can host content outside of just TigerOS on it.

IRC/TG bridges are currently under the FOSSRIT infra repo, we should get an instance for it on the new infra and then copy the relevant files here.

All RITlug infra playbooks will be in this repo (unless they're in Galaxy). I'm working with @axk4545 on this, but it's been slow due to busy schedules (particularly on my part). Basic layout will follow FOSSRIT's.

**Comment by ct-martin** [comment]
The hardest part of this is getting the base set up (and in a properly secure manner). After that's done then adding additional things should get a lot quicker

**Comment by Tjzabel** [comment]
### Update
TigerOS builder was simply turned off, and not broken. However, since there isn't much I want to salvage on it, I scrapped it, and am planning on simply bringing up a new F30 VM.

In terms of a new RITlug GitLab, I don't have any plans to move it off Titan. I think it is fine staying there, and we can always up resources on Titan for it.

**Comment by jrtechs** [comment]
I'm going to move this out of the operations board and keep it in the Tiger OS and Infra boards.

**Comment by Tjzabel** [comment]
@jrtechs sure thing.

**Comment by Tjzabel** [comment]
I've created a new VM to act as the TigerOS builder running Fedora 31. It's currently a base-install Fedora Server. My plan is to keep tabs on what extra packages I install, and any additional configurations I do. The end goal would be to have a populated [TigerOS Infrastructure](https://gitlab.com/RITlug/TigerOS/infrastructure) repo, with everything needed to spin up a new VM.

**Comment by Tjzabel** [comment]
Yeah I doubt this will ever happen.
