### ISSUE TITLE
Move out of the IST lab

### ISSUE THREAD

**Issue by ct-martin** [RITlug/config-management#17]
We've been using a personal favor & goodwill from IST to be able to have some of our new servers located in the Lab for Data Acquisition & Analytics (formerly the FET lab; across from the IST sysadmin offices) while we were trying to get them running. Unfortunately, that favor has run out and we will need to remove our servers from that lab.

We have been asked by John Simonson (the same contact as room reservation) to remove the servers, if possible, before the Fall semester starts but if not then as soon a reasonably possible. They are stacked below the table with the 3D printers, next to the window. You will need to coordinate with John on getting into the lab as it is locked (I also no longer have swipe access). He has offered access to a cart (definitely needed; the R900 is heavy) and also said that if a weekday is not possible then he may be able to come in on a weekend.

-----

For convenience (in case I forget), here are the MAC addresses of the R900:
Port 3, direct: `00:24:e8:5b:c8:2f`
Router (bridged to port 1 [top]): `fa:25:39:e8:fa:ba`
CBET router: `00:1e:2a:5e:5d:dd`

**Comment by jrtechs** [comment]
Based on Eboard's availability, the best solution is to do this the week before classes start. We will most likely be moving these servers to CBET since we really have no-where else to go with the servers on campus. The largest issue with both moving out of the FET lab and moving into the CBET datacenter is going to be finding a time that works with everyone. We will need at least 4 people on the R900 since it is very beefy and the stairs for the CBET location are steep.

**Comment by ct-martin** [comment]
@jrtechs heads up, you will likely want to make sure you can remotely get into the servers reliably (passwords in hosted GitLab) before you move them into CBET (and that you don't want to do any other maintenance). You'll also need to email the CBET admin to get down there.

**Comment by Tjzabel** [comment]
This was completed on Thursday before the start of the semester :+1: 

The R900 is currently in the Institute Hall Datacenter. Some of the old CBET servers are currently in my house.
