### ISSUE TITLE
Integrate Google Groups mailing list into RIT CampusGroups mailing list

### ISSUE THREAD

**Issue by justwheel** [RITlug/config-management#7]
~~Figure out what we need to do to meet the minimum requirements for Club Office, or if there's systems we should use to help make our club activities more transparent to club office~~

https://github.com/RITlug/tasks/issues/21#issuecomment-415992019

**Comment by ct-martin** [comment]
Issue update: after thinking about it, the overhead of moving to the FOSSRIT mailing list is going to be higher than fixing the Google Group due to the need for some members to subscribe to a new mailing list while having the same level of overhead to get integrated due to some similar restrictions on how the FOSSRIT mailing list is set up.

**Status: This issue is blocking on access to the root Gmail**
Please either give me access to the root Gmail (passwords or work together in-person) or come find me _in-person_ so I can explain why maintaining the Google Group is the recommended action.

**Comment by ct-martin** [comment]
We have decided to manually post on both the website & in CampusGroups. So far this is working well. Closing as done since further automation seems unlikely and/or very difficult.
